mural/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'postit.views.postit', name='postit'),
    url(r'^api/', include('postit.urls')),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='entrar'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}, name='sair'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

print urlpatterns

postit/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns

from api import PostList, PostDetails

urlpatterns = patterns('sgp_assessment.views',

	url(r'^posted/$', PostList.as_view(), name='post_list_endpoint'),
	url(r'^posted/(?P<pk>[^/]+)/$', PostDetails.as_view() , name='post_details_endpoint'),

)

postit/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	titulo = models.CharField(max_length=40)
	corpo = models.CharField(max_length=140)
	user = models.ForeignKey(User)
	aprovado = models.BooleanField(default=False)

	def __unicode__(self):
		return self.titulo

postit/forms.py
import django.forms as forms
from models import Post

class PostForm(forms.ModelForm):
    class Meta:
    	model = Post
    	fields = ('titulo','corpo')

    def __init__(self, *args, **kwargs):
        self.base_fields['corpo'].widget = forms.Textarea()
        super(PostForm, self).__init__(*args, **kwargs)

mural/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required

@login_required
def home(request):

    return render_to_response("home.html", locals(), context_instance=RequestContext(request))

postit/views.py
from forms import PostForm
from models import Post

from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required

@login_required
def postit(request):

	all_posts = Post.objects.filter(aprovado=True)
	print all_posts.count()
	print all_posts
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			form.instance.user = request.user
			form.save()
			form = PostForm()
	else:
		form = PostForm()
	return render_to_response('postit.html', locals(), context_instance=RequestContext(request),)

mural/templates/base.html
<!doctype html>
<html lang="pt-br" ng-app="postit">
<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock %}</title>
	<meta name="description" content="">
	<meta name="author" content="Starline">
	
	<link rel="stylesheet" href="{{ STATIC_URL }}bootstrap2/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}bootstrap2/css/bootstrap-responsive.min.css">


</head>

<body>
    {% block nav %}
     {% endblock %}
	<div class="container">
		<header class="page-header espaco-topo" >
		{% block header %}<h1>Starline Mural</h1>{% endblock header %}
		</header>
		<div class="content">
			
			{% block content %}
		        <div style="float:left; margin-left: 5px;">
		        {% block content-top %}
		         
				{% endblock %}
		        </div>
		         <div style="margin-left: 20px; float:left; width:450px;">
		         	{% block content-left %}
			        {% endblock %}
	    	     </div>
	    	     <div class="row span12" style="margin-left: 5px; margin-top: 15px; margin-bottom: -15px">
	    	     {% block content-bottom %}
	    	     {% endblock %}
	    	     </div>
			{% endblock %}

		</div>
		<footer class="row" style="text-align:center">
			<div class="span12" style="margin-top: -5px">
				<hr/>
				<p style="margin-top: -15px"><small>Starline 2014</small></p>
			</div>
		</footer>
	</div>
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}angular/angular.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}angular/angular-resource.min.js"></script>
	{% block page-scripts %}
    {% endblock %}

</body>
</html>

mural/templates/home.html
{% extends "base.html" %}

mural/templates/login.html
{% extends "base.html" %}

{% block content-bottom %}
<form method="post">
 <table>
  {% csrf_token %} <!-- -->
  {{ form }}
  <tr>
   <th>&nbsp;</th>
   <td><input type="submit" value="Entrar"/></td>
  </tr>
 </table>
</form>
{% endblock %}

mural/templates/logout.html
{% extends "base.html" %}

{% block content-bottom %}
Voce saiu do sistema. Obrigado e volte sempre!
{% endblock %}

postit/templates/postit.html
{% extends "base.html" %}

{% block page-scripts %}
<script type="text/javascript" src="{{ STATIC_URL }}postit/postit.js"></script>
{% endblock %}

{% block content-left %}

{% verbatim %}
<div ng-controller="ListPostsCtrl">
  <p ng-repeat="pst in all_posts" class="well">
    <strong>{{ pst.titulo}}</strong></br>
     {{ pst.corpo}}
     </p>
  </p>
</div>
{% endverbatim %}

{% endblock %}

{% block content-top %}
<form method="post" action={% url 'postit' %}>
 <table ng-controller="PostagemCtrl">
  {% csrf_token %} <!-- -->
  <tr>
    <th><label for="id_titulo">Titulo:</label></th>
    <td><input id="id_titulo" maxlength="40" name="titulo" type="text" /></td>
  </tr>
  <tr>
    <th><label for="id_corpo">Corpo:</label></th>
    <td><textarea cols="40" id="id_corpo" name="corpo" rows="10" ng-model="texto"></textarea></td>
  </tr>
  <tr>
    {% verbatim %}
    <td colspan='2'> Caracteres: {{ caracteres }}</td>
    {% endverbatim %}
  <tr>
  <tr>
   <th>&nbsp;</th>
   <td><input type="submit" value="Entrar"/></td>
  </tr>

 </table>
</form>
{% endblock %}